export const PUBG_MAP_LIST_REQUEST = "PUBG_MAP_LIST_REQUEST";
export const PUBG_MAP_LIST_SUCCESS = "PUBG_MAP_LIST_SUCCESS";
export const PUBG_MAP_LIST_FAIL = "PUBG_MAP_LIST_FAIL";

export const PUBG_MAP_DETAILS_REQUEST = "PUBG_MAP_DETAILS_REQUEST";
export const PUBG_MAP_DETAILS_SUCCESS = "PUBG_MAP_DETAILS_SUCCESS";
export const PUBG_MAP_DETAILS_FAIL = "PUBG_MAP_DETAILS_FAIL";
